# Настройки памяти демона Gradle + ПРИНУДИТЕЛЬНЫЙ ВЫРЕЗ БАГА NullPointerException
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dcom.android.tools.r8.disableApiModeling=1

# Стиль кода Kotlin
kotlin.code.style=official

# Использование AndroidX
android.useAndroidX=true
android.experimental.lifecycle.disableCheckAarMetadataWorkAction=true
