@file:Suppress("SpellCheckingInspection")
package com.example.mymagic

val fullInterfaceLanguagesList = listOf(
    LanguageItem("af", "Afrikaans", "", "🇿🇦"),
    LanguageItem("ka_old", "Asomtavruli", "", "🇬🇪"),
    LanguageItem("ig", "Asụsụ Igbo", "", "🇳🇬"),
    LanguageItem("gn", "Avañe'ẽ", "", "🇵🇾"),
    LanguageItem("ay", "Aymar aru", "", "🇧🇴"),
    LanguageItem("az", "Azərbaycanca", "", "🇦🇿"),
    LanguageItem("az_cyrl", "Азәрбајҹан дили", "", "🇦🇿"),
    LanguageItem("id", "Bahasa Indonesia", "", "🇮🇩"),
    LanguageItem("ms", "Bahasa Melayu", "", "🇲🇾"),
    LanguageItem("jv", "Basa Jawa", "", "🇮🇩"),
    LanguageItem("su", "Basa Sunda", "", "🇮🇩"),
    LanguageItem("be", "Беларуская", "", "🇧🇾"),
    LanguageItem("bs", "Bosanski", "", "🇧🇦"),
    LanguageItem("bg", "Български", "", "🇧🇬"),
    LanguageItem("ca", "Català", "", "🇪🇸"),
    LanguageItem("cs", "Čeština", "", "🇨🇿"),
    LanguageItem("ce", "Нохчийн мотт", "", "🇷🇺"),
    LanguageItem("ny", "Chichewa", "", "🇲🇼"),
    LanguageItem("sn", "chiShona", "", "🇿🇼"),
    LanguageItem("cy", "Cymraeg", "", "🇬🇧"),
    LanguageItem("da", "Dansk", "", "🇩🇰"),
    LanguageItem("de", "Deutsch", "", "🇩🇪"),
    LanguageItem("el", "Ελληνικά", "", "🇬🇷"),
    LanguageItem("en", "English", "", "🇬🇧"),
    LanguageItem("eo", "Esperanto", "", "💚"),
    LanguageItem("es", "Español", "", "🇪🇸"),
    LanguageItem("et", "Eesti", "", "🇪🇪"),
    LanguageItem("eu", "Euskara", "", "🇪🇸"),
    LanguageItem("fil", "Filipino", "", "🇵🇭"),
    LanguageItem("fr", "Français", "", "🇫🇷"),
    LanguageItem("fy", "Frysk", "", "🇳🇱"),
    LanguageItem("ga", "Gaeilge", "", "🇮🇪"),
    LanguageItem("gd", "Gàidhlig", "", "🇬🇧"),
    LanguageItem("sm", "Gagana Samoa", "", "🇼🇸"),
    LanguageItem("gl", "Galego", "", "🇪🇸"),
    LanguageItem("hr", "Hrvatski", "", "🇭🇷"),
    LanguageItem("ha", "Hausa", "", "🇳🇬"),
    LanguageItem("hu", "Magyar", "", "🇭🇺"),
    LanguageItem("it", "Italiano", "", "🇮🇹"),
    LanguageItem("tts", "Isan Language", "", "🇹🇭"),
    LanguageItem("is", "Íslenska", "", "🇮🇸"),
    LanguageItem("lb", "Lëtzebuergesch", "", "🇱🇺"),
    LanguageItem("to", "Lea Faka-Tonga", "", "🇹🇴"),
    LanguageItem("lt", "Lietuvių", "", "🇱🇹"),
    LanguageItem("lv", "Latviešu", "", "🇱🇻"),
    LanguageItem("ln", "Lingála", "", "🇨🇩"),
    LanguageItem("mg", "Malagasy", "", "🇲🇬"),
    LanguageItem("mt", "Malti", "", "🇲🇹"),
    LanguageItem("mk", "Македонски", "", "🇲🇰"),
    LanguageItem("no", "Norsk", "", "🇳🇴"),
    LanguageItem("nl", "Nederlands", "", "🇳🇱"),
    LanguageItem("pt", "Português", "", "🇵🇹"),
    LanguageItem("pl", "Polski", "", "🇵🇱"),
    LanguageItem("ro", "Română", "", "🇷🇴"),
    LanguageItem("qu", "Runasimi", "", "🇵🇪"),
    LanguageItem("ru", "Русский", "", "🇷🇺"),
    LanguageItem("rw", "Kinyarwanda", "", "🇷🇼"),
    LanguageItem("sq", "Shqip", "", "🇦🇱"),
    LanguageItem("sl", "Slovenščina", "", "🇸🇮"),
    LanguageItem("sk", "Slovenčina", "", "🇸🇰"),
    LanguageItem("som", "Soomaali", "", "🇸🇴"),
    LanguageItem("sr", "Српски", "", "🇷🇸"),
    LanguageItem("fi", "Suomi", "", "🇫🇮"),
    LanguageItem("fi_old", "Suomi (Wanha)", "", "🇫🇮"),
    LanguageItem("sv", "Svenska", "", "🇸🇪"),
    LanguageItem("sw", "Kiswahili", "", "🇹🇿"),
    LanguageItem("tr", "Türkçe", "", "🇹🇷"),
    LanguageItem("tk", "Türkmen dili", "", "🇹🇲"),
    LanguageItem("uk", "Українська", "", "🇺🇦"),
    LanguageItem("vi", "Tiếng Việt", "", "🇻🇳"),
    LanguageItem("yo", "Yorùbá", "", "🇳🇬"),
    LanguageItem("uz", "Oʻzbekcha", "", "🇺🇿"),
    LanguageItem("xh", "isiXhosa", "", "🇿🇦"),
    LanguageItem("zu", "isiZulu", "", "🇿🇦"),
    LanguageItem("st", "Sesotho", "", "🇿🇦"),
    LanguageItem("fj", "Na Vosa Vakaviti", "", "🇫🇯"),
    LanguageItem("la", "Latina", "", "🇻🇦"),
    LanguageItem("haw", "ʻŌlelo Hawaiʻi", "", "🇺🇸"),
    LanguageItem("mi", "Te Reo Māori", "", "🇳🇿"),
    LanguageItem("am", "አማርኛ", "", "🇪🇹"),
    LanguageItem("om", "Afaan Oromoo", "", "🇪🇹"),
    LanguageItem("as", "অসমীয়া", "", "🇮🇳"),
    LanguageItem("ka", "ქართული", "", "🇬🇪"),
    LanguageItem("ky", "Кыргызча", "", "🇰🇬"),
    LanguageItem("mn", "Монгол", "", "🇲🇳"),
    LanguageItem("tg", "Тоҷикӣ", "", "🇹🇯"),
    LanguageItem("tt", "Tatarча", "", "🍏"),
    LanguageItem("kk", "Қазақ Тілі", "", "🇰🇿"),
    LanguageItem("hy", "Հայերեն", "", "🇦🇲"),
    LanguageItem("ti", "ትግርኛ", "", "🇪🇷"),
    LanguageItem("bo", "བོད་སྐད་", "", "🇨🇳"),
    LanguageItem("th", "ไทย", "", "🇹🇭"),
    LanguageItem("lo", "ภาษาลาว", "", "🇱🇦"),
    LanguageItem("km", "ភាសាខ្មែរ", "", "🇰🇭"),
    LanguageItem("my", "မြန်မာဘာသာ", "", "🇲🇲"),
    LanguageItem("ja", "日本語", "", "🇯🇵"),
    LanguageItem("zh", "中文 (简体)", "", "🇨🇳"),
    LanguageItem("zh_tw", "中文 (繁體)", "", "🌐 "),
    LanguageItem("ko", "한국어", "", "🇰🇷"),
    LanguageItem("hi", "हिन्दी", "", "🇮🇳"),
    LanguageItem("mai", "मैथिली", "", "🇮🇳"),
    LanguageItem("ne", "नेपाली", "", "🇳🇵"),
    LanguageItem("si", "සිංහල", "", "🇱🇰"),
    LanguageItem("pa", "ਪੰਜਾਬី", "", "🇮🇳"),
    LanguageItem("gu", "ગુજરાતી", "", "🇮🇳"),
    LanguageItem("or", "ଓଡ଼ିଆ", "", "🇮🇳"),
    LanguageItem("bn", "বাংলা", "", "🇧🇩"),
    LanguageItem("mr", "मराठी", "", "🇮🇳"),
    LanguageItem("kn", "ಕನ್ನಡ", "", "🇮🇳"),
    LanguageItem("ml", "മലയാളം", "", "🇮🇳"),
    LanguageItem("ta", "தமிழ்", "", "🇮🇳"),
    LanguageItem("te", "తెలుగు", "", "🇮🇳"),
    LanguageItem("he", "עברית", "", "🇮🇱"),
    LanguageItem("ur", "اردو", "", "🇵🇰"),
    LanguageItem("ar", "العربية", "", "🇸🇦"),
    LanguageItem("fa", "فارسی", "", "🇮🇷"),
    LanguageItem("ps", "پښتو", "", "🇦🇺"),
    LanguageItem("ku", "Kurdî", "", "🇮🇶"),
    LanguageItem("ckb", "کوردیی ناوەندی", "", "🇮🇶"),
    LanguageItem("diq", "Zazaki", "", "🇹🇷"),
    LanguageItem("sd", "سنڌи", "", "🇵🇰"),
    LanguageItem("ug", "ئۇيغۇرچе", "", "🇨🇳")
)
